build:
  image: gometalinter
  commands:
    - gometalinter --vendor --deadline=60s --concurrency=1 --cyclo-over=20 --disable=gotype
    - gometalinter --vendor --deadline=60s --concurrency=1 --cyclo-over=20 --disable=gotype dtt/
    - gometalinter --vendor --deadline=60s --concurrency=1 --cyclo-over=20 --disable=gotype dtt/cmd/
